# Generated by Django 3.2.9 on 2021-12-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_repo_date_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
